os: linux
dist: xenial
language: java
jdk: openjdk11

services:
  - docker

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.local"

jobs:
  include:
    - stage: test
      name: "Test"
      script:
        - mvn clean verify
    - stage: deploy
      name: "Deploy"
      if: (branch = master)
      script: mvn clean package
      deploy:
        skip_cleanup: true
        provider: script
          - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
        on:
          branch: master
          condition: ${TRAVIS_PULL_REQUEST} = false
